export const menuItems = [
  {
    id: 1,
    tag: "Waffle",
    name: "Waffle with Berries",
    price: 6.5,
    image: "/assets/images/image-waffle-desktop.jpg",
    quantity: 1,
  },
  {
    id: 2,
    tag: "Crème Brûlée",
    name: "Vanilla Bean Crème Brûlée",
    price: 7.0,
    image: "/assets/images/image-creme-brulee-desktop.jpg",
    quantity: 1,
  },
  {
    id: 3,
    tag: "Macaron",
    name: " Macaron Mix of Five",
    price: 8.0,
    image: "/assets/images/image-macaron-desktop.jpg",
    quantity: 1,
  },
  {
    id: 4,
    tag: "Tiramisu",
    name: "Classic Tiramisu",
    price: 5.5,
    image: "/assets/images/image-tiramisu-desktop.jpg",
    quantity: 1,
  },
  {
    id: 5,
    tag: "Baklava",
    name: "Pistachio Baklava",
    price: 4.0,
    image: "/assets/images/image-baklava-desktop.jpg",
    quantity: 1,
  },
  {
    id: 6,
    tag: "Pie",
    name: "Lemon Meringue Pie",
    price: 5.0,
    image: "/assets/images/image-meringue-desktop.jpg",
    quantity: 1,
  },
  {
    id: 7,
    tag: "Cake",
    name: "Red Velvet Cake",
    price: 4.5,
    image: "/assets/images/image-cake-desktop.jpg",
    quantity: 1,
  },
  {
    id: 8,
    tag: "Brownie",
    name: "Salted Caramel Brownie",
    price: 5.5,
    image: "/assets/images/image-brownie-desktop.jpg",
    quantity: 1,
  },
  {
    id: 9,
    tag: "Panna Cotta",
    name: "Vanilla Panna Cotta",
    price: 5.5,
    image: "/assets/images/image-panna-cotta-desktop.jpg",
    quantity: 1,
  },
];
